name: Generate Snake Animation

on:
  schedule:
    # 每12小时运行一次
    - cron: "0 */12 * * *"
  # 允许手动触发
  workflow_dispatch:

# 设置权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 生成蛇形动画 SVG
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: LanceGan
          outputs: |
            dist/github-snake-dark.svg?color_snake=green&color_dots=#010101,#00d4ff

      # 部署到 output 分支
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
